DemoLinq/Controllers/LieuxController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DemoLinq.Models;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authorization;
using System.Text.Json;
using NuGet.Protocol;

namespace DemoLinq.Controllers
{
    public class LieuxController : Controller
    {
        private readonly LieuDBContext _context;

        public LieuxController(LieuDBContext context)
        {
            _context = context;
        }

        // GET: Lieux
        public async Task<IActionResult> Index(int? pageNumber)
        {
            int compteur = 0;

            if (HttpContext.Session.Keys.Contains("compteur"))
            {
                //Récupérer le compteur de la session
                compteur = (int)HttpContext.Session.GetInt32("compteur");
            }

            compteur++;

            //Stocker le compteur dans la session
            HttpContext.Session.SetInt32("compteur", compteur);
            ViewBag.Compteur = compteur;

            //Lire les resultats de la session
            if (HttpContext.Session.Keys.Contains("results"))
            { 
                string resultJson = HttpContext.Session.GetString("results");
                var resultatSession = JsonSerializer.Deserialize<List<Lieu>>(resultJson);

                ViewBag.Json = resultatSession.Count;
            }

            int pageSize = 10; // Nombre d'ingrédients par page
            return View(await PaginatedList<Lieu>.CreateAsync(
                _context.Lieux
                .Include(l => l.Livraisons)
                //.ThenInclude(l => l.Toilettes)
                .AsNoTracking(),
                pageNumber ?? 1, pageSize)); // Créer une page avec une liste paginée

           //return View(await _context.Lieux.ToListAsync());
        }

        public async Task<IActionResult> Search(string recherche, int? pageNumber)
        {
            ViewBag.Search = recherche;

            int compteur = 0;

            if (HttpContext.Session.Keys.Contains("compteur"))
            {
                //Récupérer le compteur de la session
                compteur = (int)HttpContext.Session.GetInt32("compteur");
            }

            compteur++;

            //Stocker le compteur dans la session
            HttpContext.Session.SetInt32("compteur", compteur);
            ViewBag.Compteur = compteur;
            HttpContext.Session.SetString("recherche", recherche);

            // Préparer la requête LINQ
            IQueryable<Lieu> requete = from lieu in _context.Lieux
                                       where lieu.Nom.Contains(recherche)
                                       select lieu;

            //Stocker la liste de résultats dans la session
            string jsonString = JsonSerializer.Serialize(requete.ToList());
            HttpContext.Session.SetString("results", jsonString);

            //Lire les resultats de la session
            string resultJson = HttpContext.Session.GetString("results");
            var resultatSession = JsonSerializer.Deserialize<List<Lieu>>(resultJson);

            ViewBag.Json = resultatSession.Count;

            int pageSize = 5; // Nombre d'objets par page
            return View("Index", await PaginatedList<Lieu>.CreateAsync(requete.AsNoTracking(),
                pageNumber ?? 1, pageSize)); // Créer une page avec les résultats

            // Exécuter la requête asynchrone
            //IEnumerable<Lieu> result = await requete.ToListAsync();
            //return View("Index", result);
        }
        public async Task<IActionResult> Filtre(string id, int? pageNumber)
        {
            ViewBag.Filtre = id;

            int compteur = 0;

            if (HttpContext.Session.Keys.Contains("compteur"))
            {
                //Récupérer le compteur de la session
                compteur = (int)HttpContext.Session.GetInt32("compteur");
            }

            compteur++;

            //Stocker le compteur dans la session
            HttpContext.Session.SetInt32("compteur", compteur);
            ViewBag.Compteur = compteur;
            // Préparer la requête LINQ avec expression lambda
            IQueryable<Lieu> requete = _context.Lieux.Where(l => l.Type == id);

            int pageSize = 5; // Nombre d'objets par page
            return View("Index", await PaginatedList<Lieu>.CreateAsync(requete.AsNoTracking(),
                pageNumber ?? 1, pageSize)); // Créer une page avec les résultats

            // Exécuter la requête asynchrone
            //IEnumerable<Lieu> result = await requete.ToListAsync();

            //return View("Index", result);
        }

        public async Task<IActionResult> FiltreTaille(string id, int? pageNumber)
        {
            int compteur = 0;

            if (HttpContext.Session.Keys.Contains("compteur"))
            {
                //Récupérer le compteur de la session
                compteur = (int)HttpContext.Session.GetInt32("compteur");
            }

            compteur++;

            //Stocker le compteur dans la session
            HttpContext.Session.SetInt32("compteur", compteur);
            ViewBag.Compteur = compteur;
            ViewBag.FiltreTaille = id;

            IQueryable<Lieu> requete;
            // Préparer la requête LINQ avec expression lambda
            if (id == "Grands")
            {
                requete = _context.Lieux.Where(l => l.Superficie >= 70000);
            }
            else if (id == "Moyens")
            {
                requete = _context.Lieux.Where(l => l.Superficie >= 30000 &&
                                                                l.Superficie < 70000);
            }
            else if(id == "Petits")
            {
                requete = _context.Lieux.Where(l => l.Superficie < 30000);
            }
            else
            {
                return NotFound();
            }

            int pageSize = 5; // Nombre d'objets par page
            return View("Index", await PaginatedList<Lieu>.CreateAsync(requete.AsNoTracking(),
                pageNumber ?? 1, pageSize)); // Créer une page avec les résultats

            // Exécuter la requête asynchrone
            //IEnumerable<Lieu> result = await requete.ToListAsync();

            //return View("Index", result);
        }

        // GET: Lieux/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var lieu = await _context.Lieux
                .FirstOrDefaultAsync(m => m.Id == id);
            if (lieu == null)
            {
                return NotFound();
            }

            return View(lieu);
        }

        // GET: Lieux/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Lieux/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nom,Description,Type,Latitude,Longitude,Superficie")] Lieu lieu)
        {
            if (ModelState.IsValid)
            {
                _context.Add(lieu);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(lieu);
        }

        // GET: Lieux/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var lieu = await _context.Lieux.FindAsync(id);
            if (lieu == null)
            {
                return NotFound();
            }
            return View(lieu);
        }

        // POST: Lieux/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nom,Description,Type,Latitude,Longitude,Superficie")] Lieu lieu)
        {
            if (id != lieu.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(lieu);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LieuExists(lieu.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(lieu);
        }

        // GET: Lieux/Delete/5
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var lieu = await _context.Lieux
                .FirstOrDefaultAsync(m => m.Id == id);
            if (lieu == null)
            {
                return NotFound();
            }

            return View(lieu);
        }

        // POST: Lieux/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var lieu = await _context.Lieux.FindAsync(id);
            if (lieu != null)
            {

DemoLinq/Views/Lieux/Create.cshtml
@model DemoLinq.Models.Lieu

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Lieu</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nom" class="control-label"></label>
                <input asp-for="Nom" class="form-control" />
                <span asp-validation-for="Nom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <input asp-for="Type" class="form-control" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Latitude" class="control-label"></label>
                <input asp-for="Latitude" class="form-control" />
                <span asp-validation-for="Latitude" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Longitude" class="control-label"></label>
                <input asp-for="Longitude" class="form-control" />
                <span asp-validation-for="Longitude" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Superficie" class="control-label"></label>
                <input asp-for="Superficie" class="form-control" />
                <span asp-validation-for="Superficie" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DemoLinq/Views/Lieux/Delete.cshtml
@model DemoLinq.Models.Lieu

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Lieu</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nom)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Latitude)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Latitude)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Longitude)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Longitude)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Superficie)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Superficie)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

DemoLinq/Views/Lieux/Details.cshtml
@model DemoLinq.Models.Lieu

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Lieu</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nom)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Latitude)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Latitude)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Longitude)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Longitude)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Superficie)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Superficie)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

DemoLinq/Views/Lieux/Edit.cshtml
@model DemoLinq.Models.Lieu

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Lieu</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nom" class="control-label"></label>
                <input asp-for="Nom" class="form-control" />
                <span asp-validation-for="Nom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <input asp-for="Type" class="form-control" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Latitude" class="control-label"></label>
                <input asp-for="Latitude" class="form-control" />
                <span asp-validation-for="Latitude" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Longitude" class="control-label"></label>
                <input asp-for="Longitude" class="form-control" />
                <span asp-validation-for="Longitude" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Superficie" class="control-label"></label>
                <input asp-for="Superficie" class="form-control" />
                <span asp-validation-for="Superficie" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DemoLinq/Views/Lieux/Index.cshtml
@model PaginatedList<DemoLinq.Models.Lieu>

@{
    ViewData["Title"] = "Index";

    // Conserver les paramètres de filtres ou de recherche
    var FiltreTaille = ViewBag.FiltreTaille ?? "";
    var Filtre = ViewBag.Filtre ?? "";
    var Search = ViewBag.Search ?? "";

    var id = ViewBag.FiltreTaille ?? ViewBag.Filtre ?? "";

    // Conserver l'action de contrôleur à rappeler si on a utilisé un filtre ou une recherche
    var action = "Index";
    if (FiltreTaille != "") action = "FiltreTaille";
    else if (Filtre != "") action = "Filtre";
    else if (Search != "") action = "Search";

    var l = new DemoLinq.Models.Lieu();
}

<h1>Index</h1>
<p>Nb de visites : @ViewBag.Compteur</p>
<form asp-controller="Lieux" asp-action="Search" method="get">
    <input type="text" name="recherche" id="recherche"/>
    <input type="submit" value="Chercher"/>
</form>
@ViewBag.Json résultats
<a asp-controller="Lieux" asp-action="Filtre" asp-route-id="Monument" class="btn btn-primary">
    Monuments
    </a>
<a asp-controller="Lieux" asp-action="Filtre" asp-route-id="Lac" class="btn btn-primary">
    Lacs
</a>
<a asp-controller="Lieux" asp-action="Filtre" asp-route-id="Ville" class="btn btn-primary">
    Villes
</a>
<a asp-controller="Lieux" asp-action="FiltreTaille" asp-route-id="Petits" class="btn btn-primary">
    Petits
</a>
<a asp-controller="Lieux" asp-action="FiltreTaille" asp-route-id="Moyens" class="btn btn-primary">
    Moyens
</a>
<a asp-controller="Lieux" asp-action="FiltreTaille" asp-route-id="Grands" class="btn btn-primary">
    Grands
</a>
<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(_ => l.Nom)
            </th>
            <th>
                @Html.DisplayNameFor(_ => l.Description)
            </th>
            <th>@Html.DisplayNameFor(_ => l.Type)
            </th>
            <th>@Html.DisplayNameFor(_ => l.Latitude)
            </th>
            <th>
                @Html.DisplayNameFor(_ => l.Longitude)
            </th>
            <th>
                @Html.DisplayNameFor(_ => l.Superficie)
            </th>
            <th>Livraison</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nom)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Type)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Latitude)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Longitude)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Superficie)
            </td>
            <td>
                
                    @item.Livraisons.Count
                
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>
@{
    // Gérer la pagination, avec des boutons << < > >>
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}
<a asp-action=@action
   asp-route-id=@id
   asp-route-recherche=@ViewBag.Search
   asp-route-pageNumber="@(1)"
   class="btn btn-secondary @prevDisabled">
    &lt;&lt;
</a> |
<a asp-action=@action
   asp-route-id=@id
   asp-route-recherche=@ViewBag.Search
   asp-route-pageNumber="@(Model.PageIndex - 1)"
   class="btn btn-secondary @prevDisabled">
    &lt;
</a> |
<a asp-action=@action
   asp-route-id=@id
   asp-route-recherche=@ViewBag.Search
   asp-route-pageNumber="@(Model.PageIndex + 1)"
   class="btn btn-secondary @nextDisabled">
    &gt;
</a> |
<a asp-action=@action
   asp-route-id=@id
   asp-route-recherche=@ViewBag.Search
   asp-route-pageNumber="@(Model.TotalPages)"
   class="btn btn-secondary @nextDisabled">
    &gt;&gt;
</a>